import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MessageService } from 'primeng/api';
import { ToastModule } from 'primeng/toast';
import { CardModule } from 'primeng/card';
import { ButtonModule } from 'primeng/button';
import { TabsModule } from 'primeng/tabs';
import { DatePickerModule } from 'primeng/datepicker';
import { DialogModule } from 'primeng/dialog';
import { InputTextModule } from 'primeng/inputtext';
import { CheckboxModule } from 'primeng/checkbox';

import { DataTableComponent, TableColumn, TableAction } from '../../shared/data-table/data-table.component';
import { ApiService, Schedule } from '../../../services/api.service';
import { AuthService } from '../../../services/auth.service';
import { firstValueFrom } from 'rxjs';

@Component({
  selector: 'app-schedule-management',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    DataTableComponent,
    ToastModule,
    CardModule,
    ButtonModule,
    TabsModule,
    DatePickerModule,
    DialogModule,
    InputTextModule,
    CheckboxModule,
  ],
  providers: [MessageService],
  template: `
    <div class="p-6">
      <p-card>
        <ng-template pTemplate="header">
          <div class="p-4 bg-blue-50">
            <div class="flex items-center justify-between">
              <div class="flex items-center">
                <i class="pi pi-calendar text-3xl text-blue-600 mr-3"></i>
                <div>
                  <h2 class="text-2xl font-bold text-gray-900">Schedule Management</h2>
                  <p class="text-gray-600">Create and manage work schedules with automatic employee assignment</p>
                </div>
              </div>
              <div class="flex gap-2">
                <p-button
                  label="Auto Generate Schedule"
                  icon="pi pi-magic-wand"
                  severity="success"
                  (onClick)="openAutoGenerateDialog()"
                  [disabled]="loading">
                </p-button>
                <p-button
                  label="Create Schedule"
                  icon="pi pi-plus"
                  (onClick)="openCreateDialog()"
                  [disabled]="loading">
                </p-button>
              </div>
            </div>
          </div>
        </ng-template>

        <p-tabs value="0">
          <p-tablist>
            <p-tab value="0">
              <i class="pi pi-list mr-2"></i>
              All Schedules
            </p-tab>
            <p-tab value="1">
              <i class="pi pi-calendar mr-2"></i>
              Published
            </p-tab>
            <p-tab value="2">
              <i class="pi pi-edit mr-2"></i>
              Draft
            </p-tab>
          </p-tablist>
          <p-tabpanels>
            <p-tabpanel value="0">
              <app-data-table
                [data]="schedules"
                [columns]="tableColumns"
                [actions]="tableActions"
                [loading]="loading"
                title="All Schedules"
                [showAddButton]="false">
              </app-data-table>
            </p-tabpanel>

            <p-tabpanel value="1">
              <app-data-table
                [data]="publishedSchedules"
                [columns]="tableColumns"
                [actions]="publishedActions"
                [loading]="loading"
                title="Published Schedules"
                [showAddButton]="false">
              </app-data-table>
            </p-tabpanel>

            <p-tabpanel value="2">
              <app-data-table
                [data]="draftSchedules"
                [columns]="tableColumns"
                [actions]="draftActions"
                [loading]="loading"
                title="Draft Schedules"
                [showAddButton]="false">
              </app-data-table>
            </p-tabpanel>
          </p-tabpanels>
        </p-tabs>
      </p-card>

      <!-- Auto Generate Dialog -->
      <p-dialog
        header="Auto Generate Schedule"
        [(visible)]="showAutoGenerateDialog"
        [modal]="true"
        [style]="{ width: '500px' }"
        [closable]="!formLoading">

        <div class="p-4">
          <div class="mb-4">
            <label for="scheduleName" class="block text-sm font-medium text-gray-700 mb-2">Schedule Name</label>
            <input
              pInputText
              id="scheduleName"
              [(ngModel)]="autoGenerateForm.name"
              placeholder="Enter schedule name"
              class="w-full"
              [disabled]="formLoading" />
          </div>

          <div class="mb-4">
            <label for="startDate" class="block text-sm font-medium text-gray-700 mb-2">Start Date</label>
            <p-datepicker
              id="startDate"
              [(ngModel)]="autoGenerateForm.startDate"
              placeholder="Select start date"
              class="w-full"
              [disabled]="formLoading">
            </p-datepicker>
          </div>

          <div class="mb-4">
            <label for="endDate" class="block text-sm font-medium text-gray-700 mb-2">End Date</label>
            <p-datepicker
              id="endDate"
              [(ngModel)]="autoGenerateForm.endDate"
              placeholder="Select end date"
              class="w-full"
              [disabled]="formLoading">
            </p-datepicker>
          </div>

          <div class="mb-4">
            <p-checkbox
              [(ngModel)]="autoGenerateForm.createStandardShifts"
              binary="true"
              inputId="createShifts"
              [disabled]="formLoading">
            </p-checkbox>
            <label for="createShifts" class="ml-2">Create standard shifts (9AM-2PM, 2PM-6PM, 6PM-12AM)</label>
          </div>

          <div class="mb-4">
            <p-checkbox
              [(ngModel)]="autoGenerateForm.respectRequests"
              binary="true"
              inputId="respectRequests"
              [disabled]="formLoading">
            </p-checkbox>
            <label for="respectRequests" class="ml-2">Respect employee shift requests</label>
          </div>

          <div class="bg-blue-50 p-3 rounded-lg mb-4">
            <h4 class="font-semibold text-blue-800 mb-2">What will happen:</h4>
            <ul class="text-sm text-blue-700 space-y-1">
              <li *ngIf="autoGenerateForm.createStandardShifts">• Create 3 shifts per day (Morning, Afternoon, Evening)</li>
              <li>• Automatically assign employees based on their availability</li>
              <li>• Apply scheduling rules and constraints</li>
              <li *ngIf="autoGenerateForm.respectRequests">• Prioritize employee shift requests</li>
              <li>• Generate a complete schedule ready for review</li>
            </ul>
          </div>
        </div>

        <ng-template pTemplate="footer">
          <div class="flex justify-end gap-2">
            <p-button
              label="Cancel"
              severity="secondary"
              (onClick)="closeAutoGenerateDialog()"
              [disabled]="formLoading">
            </p-button>
            <p-button
              label="Generate Schedule"
              icon="pi pi-magic-wand"
              severity="success"
              (onClick)="autoGenerateSchedule()"
              [loading]="formLoading">
            </p-button>
          </div>
        </ng-template>
      </p-dialog>

      <p-toast></p-toast>
    </div>
  `,
  styles: [`
    :host ::ng-deep .p-tabview .p-tabview-panels {
      padding: 1rem 0;
    }

    :host ::ng-deep .p-dialog .p-dialog-content {
      padding: 0;
    }
  `]
})
export class ScheduleManagementComponent implements OnInit {
  private apiService = inject(ApiService);
  private messageService = inject(MessageService);
  private authService = inject(AuthService);

  schedules: Schedule[] = [];
  loading = false;
  formLoading = false;
  showAutoGenerateDialog = false;

  autoGenerateForm = {
    name: '',
    startDate: null as Date | null,
    endDate: null as Date | null,
    createStandardShifts: true,
    respectRequests: true
  };

  tableColumns: TableColumn[] = [
    { field: 'name', header: 'Schedule Name', sortable: true, width: '200px' },
    { field: 'startDate', header: 'Start Date', type: 'date', sortable: true, width: '120px' },
    { field: 'endDate', header: 'End Date', type: 'date', sortable: true, width: '120px' },
    {
      field: 'shifts',
      header: 'Shifts',
      width: '100px',
      format: (value) => `${value?.length || 0} shifts`
    },
    {
      field: 'status',
      header: 'Status',
      type: 'tag',
      width: '100px',
      tagSeverity: (value) => {
        switch (value) {
          case 'published': return 'success';
          case 'draft': return 'warning';
          case 'archived': return 'secondary';
          default: return 'info';
        }
      },
      tagValue: (value) => value?.charAt(0).toUpperCase() + value?.slice(1)
    },
    { field: 'createdAt', header: 'Created', type: 'date', sortable: true, width: '120px' },
    { field: 'actions', header: 'Actions', type: 'actions', width: '200px' }
  ];

  tableActions: TableAction[] = [
    {
      icon: 'pi pi-eye',
      label: 'View',
      severity: 'info',
      action: (schedule) => this.viewSchedule(schedule)
    },
    {
      icon: 'pi pi-users',
      label: 'Auto Assign',
      severity: 'success',
      action: (schedule) => this.autoAssignEmployees(schedule),
      visible: (schedule) => schedule.status === 'draft'
    },
    {
      icon: 'pi pi-send',
      label: 'Publish',
      severity: 'primary',
      action: (schedule) => this.publishSchedule(schedule),
      visible: (schedule) => schedule.status === 'draft'
    },
    {
      icon: 'pi pi-trash',
      label: 'Delete',
      severity: 'danger',
      action: (schedule) => this.deleteSchedule(schedule),
      visible: (schedule) => schedule.status === 'draft'
    }
  ];

  publishedActions: TableAction[] = [
    {
      icon: 'pi pi-eye',
      label: 'View',
      severity: 'info',
      action: (schedule) => this.viewSchedule(schedule)
    },
    {
      icon: 'pi pi-download',
      label: 'Export',
      severity: 'secondary',
      action: (schedule) => this.exportSchedule(schedule)
    }
  ];

  draftActions: TableAction[] = [
    {
      icon: 'pi pi-eye',
      label: 'View',
      severity: 'info',
      action: (schedule) => this.viewSchedule(schedule)
    },
    {
      icon: 'pi pi-users',
      label: 'Auto Assign',
      severity: 'success',
      action: (schedule) => this.autoAssignEmployees(schedule)
    },
    {
      icon: 'pi pi-send',
      label: 'Publish',
      severity: 'primary',
      action: (schedule) => this.publishSchedule(schedule)
    },
    {
      icon: 'pi pi-trash',
      label: 'Delete',
      severity: 'danger',
      action: (schedule) => this.deleteSchedule(schedule)
    }
  ];

  ngOnInit(): void {
    this.loadSchedules();
  }

  get publishedSchedules(): Schedule[] {
    return this.schedules.filter(s => s.status === 'published');
  }

  get draftSchedules(): Schedule[] {
    return this.schedules.filter(s => s.status === 'draft');
  }

  async loadSchedules(): Promise<void> {
    this.loading = true;
    try {
      this.schedules = await firstValueFrom(this.apiService.getSchedules());
    } catch {
      this.messageService.add({
        severity: 'error',
        summary: 'Error',
        detail: 'Failed to load schedules'
      });
    } finally {
      this.loading = false;
    }
  }

  openAutoGenerateDialog(): void {
    this.autoGenerateForm = {
      name: `Schedule ${new Date().toLocaleDateString()}`,
      startDate: new Date(),
      endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // Next week
      createStandardShifts: true,
      respectRequests: true
    };
    this.showAutoGenerateDialog = true;
  }

  closeAutoGenerateDialog(): void {
    this.showAutoGenerateDialog = false;
  }

  openCreateDialog(): void {
    // TODO: Implement manual schedule creation
    this.messageService.add({
      severity: 'info',
      summary: 'Coming Soon',
      detail: 'Manual schedule creation will be available soon. Use Auto Generate for now.'
    });
  }

  async autoGenerateSchedule(): Promise<void> {
    if (!this.autoGenerateForm.name || !this.autoGenerateForm.startDate || !this.autoGenerateForm.endDate) {
      this.messageService.add({
        severity: 'warn',
        summary: 'Validation Error',
        detail: 'Please fill in all required fields'
      });
      return;
    }

    const currentUser = this.authService.getCurrentUser();
    if (!currentUser) {
      this.messageService.add({
        severity: 'error',
        summary: 'Authentication Error',
        detail: 'User not authenticated'
      });
      return;
    }

    this.formLoading = true;
    try {
      const payload = {
        name: this.autoGenerateForm.name,
        startDate: this.autoGenerateForm.startDate,
        endDate: this.autoGenerateForm.endDate,
        createdBy: currentUser.id,
        createStandardShifts: this.autoGenerateForm.createStandardShifts,
        respectRequests: this.autoGenerateForm.respectRequests
      };

      const newSchedule = await firstValueFrom(this.apiService.autoGenerateSchedule(payload));

      this.messageService.add({
        severity: 'success',
        summary: 'Success',
        detail: `Schedule "${newSchedule.name}" generated successfully with ${newSchedule.shifts.length} shifts`
      });

      this.closeAutoGenerateDialog();
      await this.loadSchedules();
    } catch (error: any) {
      this.messageService.add({
        severity: 'error',
        summary: 'Error',
        detail: error.message || 'Failed to generate schedule'
      });
    } finally {
      this.formLoading = false;
    }
  }

  viewSchedule(schedule: Schedule): void {
    // TODO: Navigate to schedule detail view
    this.messageService.add({
      severity: 'info',
      summary: 'Schedule Details',
      detail: `Viewing schedule: ${schedule.name}`
    });
  }

  async autoAssignEmployees(schedule: Schedule): Promise<void> {
    if (!schedule._id) return;

    try {
      this.loading = true;
      await firstValueFrom(this.apiService.autoAssignEmployees(schedule._id, true));

      this.messageService.add({
        severity: 'success',
        summary: 'Success',
        detail: 'Employees auto-assigned successfully'
      });

      await this.loadSchedules();
    } catch (error: any) {
      this.messageService.add({
        severity: 'error',
        summary: 'Error',
        detail: error.message || 'Failed to auto-assign employees'
      });
    } finally {
      this.loading = false;
    }
  }

  async publishSchedule(schedule: Schedule): Promise<void> {
    if (!schedule._id) return;

    try {
      this.loading = true;
      await firstValueFrom(this.apiService.publishSchedule(schedule._id));

      this.messageService.add({
        severity: 'success',
        summary: 'Success',
        detail: 'Schedule published successfully'
      });

      await this.loadSchedules();
    } catch (error: any) {
      this.messageService.add({
        severity: 'error',
        summary: 'Error',
        detail: error.message || 'Failed to publish schedule'
      });
    } finally {
      this.loading = false;
    }
  }

  async deleteSchedule(schedule: Schedule): Promise<void> {
    if (!schedule._id) return;

    if (confirm(`Are you sure you want to delete schedule "${schedule.name}"?`)) {
      try {
        this.loading = true;
        await firstValueFrom(this.apiService.deleteSchedule(schedule._id));

        this.messageService.add({
          severity: 'success',
          summary: 'Success',
          detail: 'Schedule deleted successfully'
        });

        await this.loadSchedules();
      } catch (error: any) {
        this.messageService.add({
          severity: 'error',
          summary: 'Error',
          detail: error.message || 'Failed to delete schedule'
        });
      } finally {
        this.loading = false;
      }
    }
  }

  exportSchedule(schedule: Schedule): void {
    // TODO: Implement schedule export
    this.messageService.add({
      severity: 'info',
      summary: 'Export',
      detail: `Exporting schedule: ${schedule.name}`
    });
  }
}
