import {
  Controller,
  Get,
  Post,
  Body,
  Patch,
  Param,
  Delete,
  UseGuards,
  Request,
} from '@nestjs/common';
import { AuthGuard } from '@nestjs/passport';
import { SchedulingService, CreateScheduleDto, GenerateScheduleDto, AutoGenerateScheduleDto } from './scheduling.service';
import { Roles } from '../auth/decorators/roles.decorator';
import { RolesGuard } from '../auth/guards/roles.guard';

@Controller('schedules')
@UseGuards(AuthGuard('jwt'))
export class SchedulingController {
  constructor(private readonly schedulingService: SchedulingService) {}

  @Post()
  @Roles('manager')
  @UseGuards(RolesGuard)
  create(@Body() createScheduleDto: CreateScheduleDto, @Request() req) {
    if (!createScheduleDto.createdBy) {
      createScheduleDto.createdBy = req.user.sub;
    }
    return this.schedulingService.create(createScheduleDto);
  }

  @Post('generate')
  @Roles('manager')
  @UseGuards(RolesGuard)
  generate(@Body() generateScheduleDto: GenerateScheduleDto, @Request() req) {
    if (!generateScheduleDto.createdBy) {
      generateScheduleDto.createdBy = req.user.sub;
    }
    return this.schedulingService.generateSchedule(generateScheduleDto);
  }

  @Post('auto-generate')
  @Roles('manager')
  @UseGuards(RolesGuard)
  autoGenerate(@Body() autoGenerateDto: AutoGenerateScheduleDto, @Request() req) {
    if (!autoGenerateDto.createdBy) {
      autoGenerateDto.createdBy = req.user.sub;
    }
    return this.schedulingService.autoGenerateScheduleWithShifts(autoGenerateDto);
  }

  @Get()
  findAll() {
    return this.schedulingService.findAll();
  }

  @Get(':id')
  findOne(@Param('id') id: string) {
    return this.schedulingService.findOne(id);
  }

  @Patch(':id/auto-assign')
  @Roles('manager')
  @UseGuards(RolesGuard)
  autoAssign(@Param('id') id: string, @Body('respectRequests') respectRequests = true) {
    return this.schedulingService.autoAssignEmployees(id, respectRequests);
  }

  @Post('auto-assign-shifts')
  @Roles('manager')
  @UseGuards(RolesGuard)
  autoAssignToShifts(@Body() body: { shiftIds: string[], respectRequests?: boolean }) {
    return this.schedulingService.autoAssignEmployeesToShifts(body.shiftIds, body.respectRequests ?? true);
  }

  @Post('auto-process-requests')
  @Roles('manager')
  @UseGuards(RolesGuard)
  autoProcessRequests(@Body() body: { shiftIds: string[] }) {
    return this.schedulingService.autoProcessShiftRequests(body.shiftIds);
  }

  @Patch(':id/publish')
  @Roles('manager')
  @UseGuards(RolesGuard)
  publish(@Param('id') id: string) {
    return this.schedulingService.publishSchedule(id);
  }

  @Delete(':id')
  @Roles('manager')
  @UseGuards(RolesGuard)
  remove(@Param('id') id: string) {
    return this.schedulingService.remove(id);
  }
}
